site_name: "My Docs"
theme:
  name: readthedocs  

nav:
  - Introduction: introduction.md
  - État de l’art: etat_de_l_art.md
  - Architecture globale: architecture_globale.md
  - Agents du système: agents_du_systeme.md
  - Architectures comparées: architectures_comparees.md
  - Mécanisme de routage intelligent: mecanisme_routage_intelligent.md
  - Mémoire et infrastructure: memoire_et_infrastructure.md
  - Implémentation: implementation.md
  - Expérimentation: experimentation.md
  - Analyse des résultats: analyse_des_resultats.md
  - Conclusion et perspectives: conclusion_et_perspectives.md
  - Livrables: livrables.md